baseURL = 'https://diegoallen.me'
languageCode = 'en-us'
title = 'Diego Allen'

[module]
  [[module.imports]]
    path = "github.com/hugo-sid/hugo-blog-awesome"

[caches]
  [caches.images]
    dir = ':cacheDir/images'