baseURL = 'https://diegoallen.me'
languageCode = 'en-us'
title = 'Diego Allen'

[module]
  [[module.imports]]
    path = "github.com/hugo-sid/hugo-blog-awesome"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  subtitle = "Software Engineer & Hobby Photographer"

  [params.author]
    avatar = "avatar.jpg" # put the file in assets folder; also ensure that image has same height and width
    # Note: image is not rendered if the resource(avatar image) is not found. No error is displayed.
    intro = "Diego's blog"
    name = "Diego Allen"
    description = "Documenting thoughts, code, side projects."

  [[menu.main]]
    pageRef="/"
    name = 'Home'
    url = '/'
    weight = 10
  [[menu.main]]
    pageRef="posts"
    name = 'Posts'
    url = '/posts/'
    weight = 20
  [[menu.main]]
    pageRef="til"
    name = 'TIL'
    url = 'https://til.diegoallen.me'
    weight = 30
  [[menu.main]]
    pageRef="about"
    name = 'About'
    url = 'https://about.diegoallen.me'
    weight = 40